### ISSUE TITLE
links in the readme dont work! 

### ISSUE THREAD

**Issue by youknowhu** [nkosarek/bramagrams#9]
i tried accessing http://www.bramagrams.com and https://bramagrams-v2.herokuapp.com/ but both result in a 404 page. 

hi nick!

**Comment by youknowhu** [comment]
hm, the links seem to work for eric though 🤔

**Comment by youknowhu** [comment]
OK update: the urls themselves work fine, but when i click on them from the readme, they redirect to `https://github.com/nkosarek/bramagrams/blob/master` which hits a 404

**Comment by nkosarek** [comment]
Sad!

`Average response time: 5mo`
